# Template

# [[cms]]
# name = ""
# description = ""
# url = ""
# github_repo = ""
# language = ""

# ---
# PHP
# ---

[[cms]]
name = "WordPress"
description = "WordPress is a free and open-source content management system (CMS) based on PHP and MySQL."
url = "https://wordpress.org"
github_repo = "WordPress/WordPress"
language = "php"

[[cms]]
name = "Drupal"
description = "Drupal is a free and open-source content-management framework written in PHP and distributed under the GNU General Public License."
url = "https://www.drupal.org"
github_repo = "drupal/drupal"
language = "php"

[[cms]]
name = "Joomla!"
description = "Joomla is a free and open-source content management system (CMS) for publishing web content. It is built on a model–view–controller web application framework that can be used independently of the CMS."
url = "https://www.joomla.org"
github_repo = "joomla/joomla-cms"
language = "php"

# -------------
# Closed Source
# -------------

[[cms]]
name = "SquareSpace"
description = "Squarespace is a SaaS-based content management system-integrated website builder, blogging platform and hosting service."
url = "https://www.squarespace.com"

[[cms]]
name = "Siteleaf"
description = "Supports Jekyll, user collaboration, publishing to AWS S3, GitHub Pages, FTP, and more."
url = "http://www.siteleaf.com"

[[cms]]
name = "ExpressionEngine"
description = "general purpose content management system written in object-oriented PHP and using MySQL for data storage."
url = "https://ellislab.com/expressionengine"

[[cms]]
name = "Craft CMS"
description = "Craft CMS is a focused content management system for developers, designers, and web professionals that blends flexibility, power, and ease of use for clients."
url = "https://craftcms.com"

[[cms]]
name = "prismic.io"
description = "A hosted, API based and developer friendly CMS backend. We take care of upgrades, scalability and security."
url = "https://prismic.io"

[[cms]]
name = "Built.io Contentstack"
description = "Headless CMS divides front-end from backend architecture to send content to multiple devices and platforms without creating content differently each time."
url = "https://www.built.io/products/contentstack/overview"

[[cms]]
name = "Osmek"
description = "Osmek is a new kind of CMS, built in the cloud so your content is available where and how you need it. It's a beautiful interface for creating content, and a powerful set of APIs for retrieving it."
url = "http://osmek.com"

[[cms]]
name = "Cloud CMS"
description = "Shatter the limits imposed by your old, legacy CMS. Our headless, API-first Content Management System provides everything needed for scalable, multi-device publishing through SaaS and On-Premise delivery"
url = "https://www.cloudcms.com"

[[cms]]
name = "Contentful"
description = "Contentful is an API-first CMS focused on the simplicity of development. Manage structured content in websites and apps."
url = "https://www.contentful.com"

# ----------
# JavaScript
# ----------

[[cms]]
name = "Netlify CMS"
description = "A CMS for Static Site Generators."
github_repo = "netlify/netlify-cms"
language = "javascript"

[[cms]]
name = "KeystoneJS"
description = "The open source framework for developing database-driven websites, applications and APIs in Node.js. Built on Express and MongoDB."
url = "http://keystonejs.com"
github_repo = "keystonejs/keystone"
language = "javascript"

[[cms]]
name = "Relax"
description = "New generation CMS on top of React, Redux and GraphQL."
github_repo = "relax/relax"
language = "javascript"

[[cms]]
name = "Ghost"
description = "Ghost is an open source publishing platform which is beautifully designed, easy to use, and free for everyone."
url = "https://ghost.org"
github_repo = "tryghost/Ghost"
language = "javascript"

[[cms]]
name = "We.js Framework"
description = "Extensible Node.js MVC framework."
url = "http://wejs.org/"
github_repo = "wejs/we"
language = "javascript"

[[cms]]
name = "PencilBlue"
description = "Business class content management for Node.js (plugins, server cluster management, data-driven pages)."
url = "https://pencilblue.org"
github_repo = "pencilblue/pencilblue"
language = "javascript"

[[cms]]
name = "Cody"
description = "Javascript Content Management System running on Node.js."
url = "http://howest.cody-cms.org"
github_repo = "jcoppieters/cody"
language = "javascript"

[[cms]]
name = "Apostrophe"
description = "Apostrophe is a content management system. This core module provides rich content editing as well as essential services to tie Apostrophe to your Express application."
github_repo = "punkave/apostrophe"
language = "javascript"

[[cms]]
name = "Reaction"
description = "Reaction is a modern reactive, real-time event driven ecommerce platform."
url = "https://reactioncommerce.com/"
github_repo = "reactioncommerce/reaction"
language = "javascript"

[[cms]]
name = "Directus"
description = "Directus is a headless CMS written in backbone.js that provides a feature-rich environment for rapid development and management of custom database schemas."
url = "http://getdirectus.com"
github_repo = "directus/directus"
language = "javascript"

# ----
# Ruby
# ----

[[cms]]
name = "Alchemy CMS"
description = "Alchemy is a powerful, flexible and user centric Rails CMS."
url = "http://alchemy-cms.com"
github_repo = "AlchemyCMS/alchemy_cms"
language = "ruby"

[[cms]]
name = "Camaleon CMS"
description = "Camaleon CMS is a dynamic and advanced content management system based on Ruby on Rails 4."
url = "http://camaleon.tuzitio.com/"
github_repo = "owen2345/camaleon-cms"
language = "javascript"

[[cms]]
name = "ComfortableMexicanSofa "
description = "ComfortableMexicanSofa is a powerful Rails 4 CMS Engine."
github_repo = "comfy/comfortable-mexican-sofa"
language = "ruby"

[[cms]]
name = "LocomotiveCMS"
description = "A platform to create, publish and edit sites."
url = "http://locomotive.works"
github_repo = "locomotivecms/engine"
language = "ruby"

[[cms]]
name = "Publify"
description = "A self hosted Web publishing platform on Rails."
url = "http://publify.co"
github_repo = "publify/publify"
language = "ruby"

[[cms]]
name = "Radiant CMS"
description = "Radiant is a no-fluff, open source content management system designed for small teams."
url = "http://radiantcms.org/"
github_repo = "radiant/radiant"
language = "ruby"

[[cms]]
name = "Refinery CMS"
description = "An extendable Ruby on Rails CMS that supports Rails 4.2+."
url = "http://refinerycms.com"
github_repo = "refinery/refinerycms"
language = "ruby"

[[cms]]
name = "Spina"
description = "GitHub - denkGroot/Spina: Spina CMS."
url = "http://www.spinacms.com"
github_repo = "denkGroot/Spina"
language = "ruby"

[[cms]]
name = "Storytime"
description = "Storytime is a Rails 4+ CMS and blogging engine, with a core focus on content. It is built and maintained by @cultivatelabs."
github_repo = "CultivateLabs/storytime"
language = "ruby"

## ------
## Python
## ------

[[cms]]
name = "django CMS"
description = "The easy-to-use and developer-friendly CMS."
url = "http://www.django-cms.org"
github_repo = "divio/django-cms"
language = "python"

[[cms]]
name = "feinCMS"
description = "A Django-based CMS with a focus on extensibility and concise code."
url = "http://www.feincms.org/"
github_repo = "feincms/feincms"
language = "python"

[[cms]]
name = "Kotti"
description = "Kotti is a high-level, Pythonic web application framework based on Pyramid and SQLAlchemy. It includes an extensible Content Management System called the Kotti CMS."
url = "http://kotti.pylonsproject.org"
github_repo = "Kotti/Kotti"
language = "python"

[[cms]]
name = "Mezzanine"
description = "CMS framework for Django."
url = "http://mezzanine.jupo.org"
github_repo = "stephenmcd/mezzanine"
language = "python"

[[cms]]
name = "Opps Project"
description = "A Django-based CMS for the magazines, newspappers websites and portals with high-traffic."
url = "http://opps.github.io/opps/"
github_repo = "opps/opps"
language = "python"

[[cms]]
name = "Plone CMS"
description = "Plone is a user friendly Content Management System running on top of Python, Zope and the CMF."
url = "http://plone.org"
github_repo = "plone/Plone"
language = "python"

[[cms]]
name = "Quokka CMS"
description = "Quokka is a flexible content management platform powered by Python, Flask and MongoDB."
url = "http://www.quokkaproject.org"
github_repo = "quokkaproject/quokka"
language = "python"

[[cms]]
name = "Wagtail CMS"
description = "Wagtail is a content management system built on Django. It's focused on user experience, and offers precise control for designers and developers."
url = "http://wagtail.io"
github_repo = "torchbox/wagtail"
language = "python"
